# ========================================================================================
# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
# Welcome to Jekyll!
# ----------------------------------------------------------------
# Site settings
# ----------------------------------------------------------------
# References: not included elsewhere, otherwise check each section
# ----------------------------------------------------------------
# https://www.w3schools.com/w3css/default.asp
# https://fontawesome.com/docs/web/setup/host-yourself/webfonts4
# https://realfavicongenerator.net/
# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
# ========================================================================================

# ========================================================================================
# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
# Jekyll settings
# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
# ========================================================================================

# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
# ---------------------------------------------------------------
# This site requires sass-embedded
# https://github.com/jekyll/jekyll-sass-converter#sass-embedded
# ---------------------------------------------------------------
sass:
  implementation: sass-embedded
  style: compressed
# ---------------------------------------------------------------

# ---------------------------------------------------------------
# Exclude from processing:
# ---------------------------------------------------------------
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/
  - README.md
  - LICENSE
  - Makefile
  - Makefile.py
  - __pycache__

# ---------------------------------------------------------------
# Markdown Processors
# ---------------------------------------------------------------
markdown: kramdown
#kramdown:
#  syntax_highlighter: rouge
#  syntax_highlighter_opts:
#    block:
#      line_numbers: false

#kramdown:
#  syntax_highlighter: coderay
#  syntax_highlighter_opts:
#    line_numbers: false

# ---------------------------------------------------------------
# Code highlight-js
# ---------------------------------------------------------------
# https://highlightjs.org/download/
# https://jojozhuang.github.io/tutorial/jekyll-highlighting/
# https://github.com/wcoder/highlightjs-line-numbers.js/
# Styles:
#  https://highlightjs.org/static/demo/ (with inspect website, copy .css urls)
# ---------------------------------------------------------------
highlightjs: true
highlight_lno: false
#highlightjs_theme: //cdnjs.cloudflare.com/ajax/libs/highlight.js/11.5.1/styles/default.min.css
highlightjs_theme: https://highlightjs.org/static/demo/styles/atom-one-dark-reasonable.css
kramdown:
    syntax_highlighter_opts:
      disable: true
# ---------------------------------------------------------------
# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

# ========================================================================================
# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
# Site settings
# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
# ========================================================================================
# https://www.w3schools.com/w3css/w3css_color_themes.asp
w3_theme: https://www.w3schools.com/lib/w3-theme-teal.css

lang: en-CA

# https://fonts.google.com/
google_font: https://fonts.googleapis.com/css2?family=Open+Sans
google_font_family: "'Open Sans', sans-serif;"

# Layout
sidebar_w: 360px

# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
# ---------------------------------------------------------------
# Plugins
# ---------------------------------------------------------------
# https://github.com/jekyll/jekyll-seo-tag
# https://github.com/jeffreytse/jekyll-spaceship
# https://github.com/allejo/jekyll-toc
# ---------------------------------------------------------------
#  - jekyll-feed
plugins:
  - jekyll-seo-tag
  - jekyll-spaceship

# ---------------------------------------------------------------
# Google Analytics
# ---------------------------------------------------------------
# https://desiredpersona.com/google-analytics-jekyll/
# ---------------------------------------------------------------
google_analytics:
  id:
  # Google Analytics pageviews report settings
  pv:
    proxy_endpoint:
# ---------------------------------------------------------------

# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
# ---------------------------------------------------------------
# https://github.com/penibelst/jekyll-compress-html
# ---------------------------------------------------------------
compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]
  endings: all
  ignore:
    envs: [local, development]
  blanklines: false
  profile: false

# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
# ------------ Jekyll Archive Options ------------------
jekyll-archives:
  enabled: [categories, tags]
  layouts:
    category: category
    tag: tag
  permalinks:
    tag: /tags/:name/
    category: /categories/:name/

# ========================================================================================
# User settings
# ========================================================================================
# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
# ---------------------------------------------------------------
# jekyll-seo-tag settings (plugin, but uses common jeckyll variables)
# ---------------------------------------------------------------
# https://github.com/jekyll/jekyll-seo-tag/blob/master/docs/usage.md
# ---------------------------------------------------------------
title: Danilo Ramos, MSc, P.Eng.
tagline: Embedded Systems Design, Tutorials, Projects and Guides

description: >-                        # used by seo meta and the atom feed
  Personal blog and website for Embedded Systems Designs
  Tutorials, Projects with MCU, FPGAs

# fill in the protocol & hostname for your site, e.g., 'https://username.github.io'
url: 'https://dramoz.github.io'
logo: 'assets/img/avatar.png'

github:
  username: dramoz

twitter:
  username: dramoz1977

social:
  # Change to your full name.
  # It will be displayed as the default author of the posts and the copyright owner in the Footer
  name: Danilo Ramos
  email: dramoz@gmail.com
  links:
    # The first element serves as the copyright owner's link
    - https://github.com/dramoz
    - https://community.element14.com/members/dramoz
    - https://www.hackster.io/dramoz
    - https://www.linkedin.com/in/dramoz
    # Uncomment below to add more social links
    # - https://www.facebook.com/username

google_site_verification: google-site-verification=e8PlCoi0UOY5SGE60r1luNuxmYoKY_XI9va3CGm_oQg
# ---------------------------------------------------------------

# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
# ---------------------------------------------------------------
# Collections
# ---------------------------------------------------------------
collections:
  blogs:
    output: true
    permalink: /:collection/:path
  
  tutorials:
    output: true
    permalink: /:collection/:path
  
  projects:
    output: true
    permalink: /:collection/:path

# Defaults
defaults:
  -
    scope:
      path: ""
    values:
      layout: "page"
    
  -
    scope:
      path: "_tutorials"
    values:
      toc: true
  -
    scope:
      path: "_blogs"
    values:
      toc: true

# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
# ------------ Jekyll Compose Options ------------------
# Add line to Gemfile
# gem 'jekyll-compose', group: [:jekyll_plugins]
jekyll_compose:
  auto_open: true
  default_front_matter:
    posts:
      categories: 
      tags:
      math: true
      mermaid: true
      image:
        src: assests/img/title/s
        width: 400   # in pixels
        height: 400   # in pixels
        alt: image alternative text
      pin: false
